#!/usr/bin/env python3
"""Analyze duplicate and redundant package records in the inventory CSV.

This script reads the normalized package inventory generated by
`scripts/spdx_package_inventory.py`, groups records by package name and by exact
name/version, classifies duplicate and suspicious records, and writes a Markdown
report for review.

The analysis covers:
- exact duplicate name/version records
- packages with multiple versions
- likely version-format duplicates, such as 1.12 and 1.12.0
- suspicious versions, such as blank, 0.0.0, UNKNOWN, dirty, and untagged

Example:
    python3 scripts/deduplication_analysis.py \
        --input reports/package-inventory.csv \
        --output reports/deduplication-analysis.md
"""

from __future__ import annotations

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path

SUSPICIOUS_VERSION_VALUES = {
    "",
    "0.0.0",
    "unknown",
    "dirty",
    "untagged",
    "undefined",
    "none",
    "null",
    "noassertion",
}
SUSPICIOUS_VERSION_PARTS = ("unknown", "dirty", "untagged")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a Markdown deduplication analysis from package-inventory.csv."
    )
    parser.add_argument(
        "--input",
        "-i",
        default="reports/package-inventory.csv",
        help="Input package inventory CSV. Default: reports/package-inventory.csv",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="reports/deduplication-analysis.md",
        help="Output Markdown report. Parent directories are created automatically. Default: reports/deduplication-analysis.md",
    )
    return parser.parse_args()


def is_suspicious_version(version: str) -> bool:
    value = (version or "").strip().lower()
    return value in SUSPICIOUS_VERSION_VALUES or any(
        part in value for part in SUSPICIOUS_VERSION_PARTS
    )


def normalized_version(version: str) -> str:
    """Normalize only conservative display-format differences for comparison.

    This intentionally avoids full package-version parsing. The goal is to catch
    obvious formatting-only variants, such as `1.12` and `1.12.0`, without
    incorrectly merging different release schemes.
    """
    value = (version or "").strip().lower()
    value = re.sub(r"^v", "", value)
    match = re.fullmatch(r"(\d+(?:\.\d+)*)(.*)", value)
    if not match:
        return value

    parts = match.group(1).split(".")
    suffix = match.group(2)
    while len(parts) > 1 and parts[-1] == "0":
        parts.pop()
    return ".".join(parts) + suffix


def markdown_escape(value: str) -> str:
    return (value or "").replace("|", "\\|").replace("\n", " ")


def version_list(records: list[dict[str, str]]) -> str:
    versions = sorted(
        {record["version"] if record["version"] else "<blank>" for record in records},
        key=str.lower,
    )
    return ", ".join(f"`{markdown_escape(version)}`" for version in versions)


def ecosystem_list(records: list[dict[str, str]]) -> str:
    ecosystems = sorted({record["ecosystem"] for record in records}, key=str.lower)
    return ", ".join(f"`{markdown_escape(ecosystem)}`" for ecosystem in ecosystems)


def build_indexes(
    records: list[dict[str, str]],
) -> tuple[dict[str, list[dict[str, str]]], dict[tuple[str, str], list[dict[str, str]]]]:
    by_name: dict[str, list[dict[str, str]]] = defaultdict(list)
    by_name_version: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)

    for record in records:
        by_name[record["name"]].append(record)
        by_name_version[(record["name"], record["version"])].append(record)

    return by_name, by_name_version


def find_format_duplicate_names(by_name: dict[str, list[dict[str, str]]]) -> set[str]:
    names = set()
    for name, records in by_name.items():
        if len({record["version"] for record in records}) <= 1:
            continue

        normalized_groups: dict[str, set[str]] = defaultdict(set)
        for record in records:
            normalized_groups[normalized_version(record["version"])].add(record["version"])

        if any(len(versions) > 1 for versions in normalized_groups.values()):
            names.add(name)

    return names


def classify(
    name: str,
    records: list[dict[str, str]],
    by_name_version: dict[tuple[str, str], list[dict[str, str]]],
    format_duplicate_names: set[str],
) -> str:
    versions = {record["version"] for record in records}
    ecosystems = {record["ecosystem"] for record in records}
    has_exact_duplicate = any(
        len(by_name_version[(name, version)]) > 1 for version in versions
    )
    has_multiple_versions = len(versions) > 1
    has_suspicious_version = any(
        record.get("has_suspicious_version") == "True"
        or is_suspicious_version(record["version"])
        for record in records
    )

    if has_suspicious_version and has_multiple_versions:
        return (
            "Suspicious version plus another recorded version; likely cleanup "
            "candidate / stale installed metadata rather than intentional coexistence."
        )
    if has_suspicious_version:
        if any("/site-packages/setuptools/" in record.get("source_info", "") for record in records):
            return (
                "Suspicious `UNKNOWN` executable version from bundled setuptools "
                "launcher binary; bundled binary/package artifact."
            )
        if name.startswith(".pixi/"):
            return (
                "Document-root directory record with blank version; normal Syft "
                "directory/package boundary artifact."
            )
        return "Suspicious version metadata; cleanup candidate."
    if name in format_duplicate_names:
        return (
            "Likely version-format duplicate (trailing `.0` normalization); conda + "
            "PyPI duplicate, not clear separate installed versions."
        )
    if has_multiple_versions:
        return (
            "Actual simultaneous multiple versions recorded across ecosystems; verify "
            "environment resolution and import path precedence."
        )
    if has_exact_duplicate:
        if ecosystems == {"conda", "pypi"}:
            return (
                "Normal Syft duplication from conda package metadata plus installed "
                "Python distribution metadata."
            )
        if ecosystems == {"conda", "generic"}:
            return (
                "Bundled binary/package artifact: executable/library detected "
                "separately from the conda package record."
            )
        if ecosystems == {"python"}:
            return (
                "Bundled binary/package artifact: multiple architecture-specific "
                "launcher executables share one product/version."
            )
        return "Exact duplicate name/version records across ecosystems; review scanner source records."
    return "No deduplication concern."


def followup(concern: str) -> str:
    if "Normal Syft duplication" in concern:
        return (
            "Deduplicate in reporting by preferring one package identity per `name` + "
            "`version`; keep both source references if traceability is needed."
        )
    if "version-format duplicate" in concern:
        return (
            "Normalize semantic versions for comparison (`1.12` == `1.12.0`) and "
            "confirm both records point to the same installed package."
        )
    if "Actual simultaneous" in concern:
        return (
            "Check lockfile/conda metadata and Python dist-info; decide whether both "
            "versions are expected, then document or remove stale metadata."
        )
    if "Suspicious version plus another" in concern:
        return (
            "Inspect the PyPI `.dist-info` direct URL/metadata and reinstall or clean "
            "stale editable/local metadata if the conda version is authoritative."
        )
    if "setuptools launcher" in concern:
        return (
            "Treat as bundled executable metadata; optionally suppress binary "
            "pseudo-packages from package inventory totals."
        )
    if "Document-root directory" in concern:
        return "Exclude document-root directory records from package deduplication metrics."
    if "Suspicious version metadata" in concern:
        return "Inspect source metadata and replace with a real release/version if it is a first-party package."
    if "Bundled binary/package artifact" in concern:
        return (
            "Keep as evidence of bundled executable artifact, but avoid counting it as "
            "an additional installed package."
        )
    return "Review manually."


def build_report(records: list[dict[str, str]]) -> str:
    by_name, by_name_version = build_indexes(records)
    exact_duplicates = {
        key: duplicates
        for key, duplicates in by_name_version.items()
        if len(duplicates) > 1
    }
    multiple_version_names = {
        name: duplicates
        for name, duplicates in by_name.items()
        if len({record["version"] for record in duplicates}) > 1
    }
    format_duplicate_names = find_format_duplicate_names(by_name)
    suspicious_names = {
        record["name"]
        for record in records
        if record.get("has_suspicious_version") == "True"
        or is_suspicious_version(record["version"])
    }
    finding_names = sorted(
        {name for name, _version in exact_duplicates}
        | set(multiple_version_names)
        | suspicious_names,
        key=str.lower,
    )

    exact_conda_pypi = sum(
        1
        for duplicates in exact_duplicates.values()
        if {record["ecosystem"] for record in duplicates} == {"conda", "pypi"}
    )
    exact_conda_generic = sum(
        1
        for duplicates in exact_duplicates.values()
        if {record["ecosystem"] for record in duplicates} == {"conda", "generic"}
    )
    exact_python = sum(
        1
        for duplicates in exact_duplicates.values()
        if {record["ecosystem"] for record in duplicates} == {"python"}
    )
    suspicious_record_count = sum(
        1
        for record in records
        if record.get("has_suspicious_version") == "True"
        or is_suspicious_version(record["version"])
    )

    lines = [
        "# Package deduplication analysis",
        "",
        "Source: `reports/package-inventory.csv`.",
        "",
        "## Summary",
        "",
        f"- Total package records: **{len(records)}**",
        f"- Unique package names: **{len(by_name)}**",
        f"- Exact duplicate `name` + `version` groups: **{len(exact_duplicates)}**",
        f"  - `conda` + `pypi` metadata overlaps: **{exact_conda_pypi}**",
        f"  - `conda` + `generic` binary/package overlaps: **{exact_conda_generic}**",
        f"  - Python bundled launcher duplicate group(s): **{exact_python}**",
        f"- Package names with multiple versions: **{len(multiple_version_names)}**",
        f"- Likely version-format duplicate package names: **{len(format_duplicate_names)}**",
        f"- Suspicious-version records: **{suspicious_record_count}** across **{len(suspicious_names)}** package names",
        "",
        "## Method",
        "",
        "The inventory was grouped first by `name`, then by exact `name` + `version`. Findings below include packages that have exact duplicate name/version records, multiple versions for one name, likely formatting-only version differences such as trailing-zero semver differences, or suspicious versions such as blank, `UNKNOWN`, `0.0.0`, `unknown`, `dirty`, and `untagged`.",
        "",
        "## Interpretation",
        "",
        "- Most exact duplicate records are expected Syft behavior in this environment: Syft sees both conda metadata and Python package metadata for the same installed distribution.",
        "- `conda` + `generic` duplicates are executable or library artifacts such as `/bin/python3.13`, `/bin/openssl`, `/bin/jq`, and `/bin/zstd` that are also represented by conda package metadata.",
        "- Suspicious `UNKNOWN` launcher records come from bundled Windows executable launchers inside `setuptools`; the repeated `Simple Launcher` records come from architecture-specific launcher binaries vendored under `pip/_vendor/distlib`.",
        "- Multi-version rows are higher-priority follow-up items because they can indicate actual version skew, stale `.dist-info` metadata, or formatting-only version differences.",
        "",
        "## Findings",
        "",
        "| package | versions | record count | ecosystem(s) | concern | recommended follow-up |",
        "|---|---:|---:|---|---|---|",
    ]

    for name in finding_names:
        package_records = by_name[name]
        concern = classify(name, package_records, by_name_version, format_duplicate_names)
        lines.append(
            f"| `{markdown_escape(name)}` | {version_list(package_records)} | "
            f"{len(package_records)} | {ecosystem_list(package_records)} | "
            f"{markdown_escape(concern)} | {markdown_escape(followup(concern))} |"
        )

    lines.extend(["", "## Higher-priority follow-up", ""])
    for name in sorted(set(multiple_version_names) | suspicious_names, key=str.lower):
        package_records = by_name[name]
        concern = classify(name, package_records, by_name_version, format_duplicate_names)
        lines.append(f"- `{markdown_escape(name)}` ({version_list(package_records)}): {markdown_escape(concern)}")

    lines.extend(
        [
            "",
            "## Deduplication recommendations",
            "",
            "1. For routine inventory counts, collapse exact duplicate `name` + `version` records when the ecosystems are `conda` + `pypi`; retain both source references if provenance matters.",
            "2. Do not treat `conda` + `generic` binary overlaps as separate application dependencies unless binary-level artifact tracking is explicitly required.",
            "3. Suppress or separately bucket bundled launcher pseudo-packages (`Simple Launcher`, `cli*`, `gui*`) so they do not inflate package counts.",
            "4. Normalize semver-like versions before comparing packages, especially trailing-zero variants such as `1.12` and `1.12.0`.",
            "5. Manually inspect multi-version and suspicious-version packages before cleanup; several look like stale or locally generated Python `.dist-info` metadata next to authoritative conda packages.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    with input_path.open(newline="", encoding="utf-8") as f:
        records = list(csv.DictReader(f))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_report(records), encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
