name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: openfe
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .pixi/envs/openfe
          config: syft.yaml
          upload-release-assets: false
